name: CI

on: [push, pull_request]

jobs:
  build_docs:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ['14', '16', '18']
    name: Build docs
    runs-on: ${{ matrix.platform }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: yarn install --frozen-lockfile --ignore-engines --ignore-scripts
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          working-dir: docs
          deploy-branch: gh-pages
